# -*- coding: utf-8 -*-
"""calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qpyurwsg-hpKq_Vne7Efs-T0-cAi33Yc
"""

import math

print("=== CALCULADORA ===")
print("1  - Soma")
print("2  - Subtração")
print("3  - Multiplicação")
print("4  - Divisão")
print("5  - Divisão Inteira")
print("6  - Resto da Divisão (Módulo)")
print("7  - Potência")
print("8  - Raiz Quadrada")
print("9  - Raiz N-ésima")
print("10 - Logaritmo (base N)")
print("11 - Média Aritmética")
print("12 - Porcentagem (% de N)")
print("13 - Regra de Três Simples")
print("14 - Área do Retângulo")
print("15 - Hipotenusa (Pitágoras)")
print("16 - Fatorial")
print("17 - Seno")
print("18 - Cosseno")
print("19 - Tangente")
print("20 - MMC (Mínimo Múltiplo Comum)")

opcao = input("Escolha uma opção: ")
num1 = float(input("Digite o primeiro número: "))
num2 = float(input("Digite o segundo número: "))

if opcao == "1":
    resultado = num1 + num2
    print("Resultado:", resultado)
elif opcao == "2":
    resultado = num1 - num2
    print("Resultado:", resultado)
elif opcao == "3":
    resultado = num1 * num2
    print("Resultado:", resultado)
elif opcao == "4":
    if num2 == 0:
        print("Erro: divisão por zero")
    else:
        resultado = num1 / num2
        print("Resultado:", resultado)
elif opcao == "5":
    if num2 == 0:
        print("Erro: divisão por zero")
    else:
        resultado = int(num1) // int(num2)
        print("Resultado:", resultado)
elif opcao == "6":
    if num2 == 0:
        print("Erro: divisão por zero")
    else:
        resultado = num1 % num2
        print("Resultado:", resultado)
elif opcao == "7":
    resultado = num1 ** num2
    print("Resultado:", resultado)
elif opcao == "8":
    if num1 < 0:
        print("Erro: raiz quadrada de número negativo")
    else:
        resultado = math.sqrt(num1)
        print("Resultado:", resultado)
elif opcao == "9":
    if num2 == 0:
        print("Erro: índice da raiz não pode ser zero")
    else:
        resultado = num1 ** (1 / num2)
        print("Resultado:", resultado)
elif opcao == "10":
    if num1 <= 0:
        print("Erro: logaritmo de número não positivo")
    elif num2 <= 0 or num2 == 1:
        print("Erro: base do logaritmo inválida")
    else:
        resultado = math.log(num1, num2)
        print("Resultado:", resultado)
elif opcao == "11":
    resultado = (num1 + num2) / 2
    print("Resultado:", resultado)
elif opcao == "12":
    resultado = (num2 / 100) * num1
    print("Resultado:", resultado)
elif opcao == "13":
    if num1 == 0:
        print("Erro: primeiro número não pode ser zero")
    else:
        resultado = (num2 * num1) / num1
        print("Resultado:", resultado)
elif opcao == "14":
    resultado = num1 * num2
    print("Resultado:", resultado)
elif opcao == "15":
    resultado = math.sqrt(num1 ** 2 + num2 ** 2)
    print("Resultado:", resultado)
elif opcao == "16":
    if num1 < 0:
        print("Erro: fatorial de número negativo")
    else:
        resultado = math.factorial(int(num1))
        print("Resultado:", resultado)
elif opcao == "17":
    resultado = math.sin(math.radians(num1))
    print("Resultado:", resultado)
elif opcao == "18":
    resultado = math.cos(math.radians(num1))
    print("Resultado:", resultado)
elif opcao == "19":
    if num1 % 90 == 0 and num1 % 180 != 0:
        print("Erro: tangente indefinida para esse ângulo")
    else:
        resultado = math.tan(math.radians(num1))
        print("Resultado:", resultado)
elif opcao == "20":
    resultado = math.lcm(int(num1), int(num2))
    print("Resultado:", resultado)
else:
    print("Opção inválida")